forge "https://forgeapi.puppetlabs.com"
moduledir 'modules'
# A module from the Puppet Forge
mod 'puppetlabs-stdlib'
mod 'puppetlabs-apache'
# mod 'puppetlabs-ntp'

moduledir  'homegrown'
mod 'puppetlabs-mysql', '3.10.0'
mod 'puppetlabs-firewall', :latest
# A module from git
#mod 'puppetlabs-ntp',
#  :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# A module from a git branch/tag
mod 'puppetlabs-apt',
  :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
  :ref => '1.4.x'

# A module from Github pre-packaged tarball
# mod 'puppetlabs-apache', '0.6.0', :github_tarball => 'puppetlabs/puppetlabs-apache'
