---
driver:
  name: gce
  project: my_project-infraci-sbx
  region: us-central1
  network: sandbox
  subnet: sandbox-ci-cd-prv01
  disk_size: 40
  use_private_ip: true
  tags:
    - test-kitchen

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
  hiera_data_path: hieradata
  require_chef_for_busser: false
  require_puppet_collections: true
  puppet_detailed_exitcodes: true
  puppet_whitelist_exit_code:
    - 0
    - 2

verifier:
  ruby_bindir: '/opt/puppetlabs/puppet/bin'
  name: inspec

platforms:
  - name: puppet_apply-rhel-7
    driver:
      image_project: my_project-infraci-sbx
      image_name: my_project-rhel7-puppetci-1495490509
  - name: puppet_apply-rhel6
    driver:
      image_project: my_project-infraci-sbx
      image_name: my_project-rhel6-puppetci-1495489777

transport:
  username: TKMAITG
  ssh_key: ~/.ssh/google_compute_engine

suites:
  - name: sfp
    verifier:
      inspec_tests:
        - path: modules/simple_file_demo/test/acceptance/default_spec.rb
  - name: te2
    verifier:
      inspec_tests:
        - path: modules/test_example_2/test/acceptance/default_spec.rb